export const SWITCH_ENGLISH = 'SWITCH_ENGLISH';
export const SWITCH_RUSSIAN = 'SWITCH_RUSSIAN';
export const SHOW_CELSIUS = 'SHOW_CELSIUS';
export const SHOW_FAHRENHEIT = 'SHOW_FAHRENHEIT';

export const USERS_CITY = 'USERS_CITY';
export const USERS_COUNTRY = 'USERS_COUNTRY';
export const USERS_TIMEZONE = 'USERS_TIMEZONE';